[serviceweaver]
name = "demo-service-weaver"
binary = "./demo-service-weaver"

[gke]
regions = ["europe-west1"]
public_listener = [
    {name = "hello", hostname = "demo-service-weaver.dev.blogic.tech"},
]